#!/bin/bash 

PLOT_FILE=$1
DIR=$2
FILE=$3;

START=$4;
END=$5;
SCALE=$6

dat=$START

echo " "
echo "Bash script for many aztekas plots"
echo ""

plot_file=$FILE$dat".dat"

if [ -z "$PLOT_FILE" ] || [ -z $DIR ] || [ -z $FILE ] || [ -z $START ] || [ -z $END ] || [ -z $SCALE ]
then
   echo "Execute this file in your terminal as:"
   echo "   ./frames PLOT_FILE DIR FILE START END SCALE"
   echo "where"
   echo "   PLOT_FILE: Python or gnuplot script with path"
   echo "   DIR: Path of the directory with the *.dat files. If"
   echo "        you are inside that directory write ."
   echo "   FILE: Characteristic name of the aztekas files, e.g."
   echo "         from sim_*.dat, FILE = sim_"
   echo "   START: File number from with you want to start"
   echo "   END: Last file number you want to plot"
   echo "   SCALE: 'lin' for linear and 'log' for logarithmic"
   echo " "
else
   scale=$(echo "x = l($END)/l(10); scale = 0; (x / 1) + 1" | bc -l)
   while [ $dat -lt $((END+1)) ];
   do
   num=$(echo "scale = $scale; ($dat/(10^$scale))" | bc -l)

   if [ $dat -eq 0 ] 
   then
      num=.0
      append=1
      while [ $append -lt $scale ]
      do
         num+=0
         append=$((append+1))
      done
   fi

   echo "Plotting file" $plot_file
   if [ -f $plot_file ]
   then
      touch "$FILE""$num".png
      change=`echo "$FILE""$num"".png" | sed 's/\.//'`
      mv "$FILE""$num".png $change

      "$PLOT_FILE" "$DIR"/"$FILE""$dat".dat $change $SCALE
      echo "Done! ->" $change
      echo " "
   else
      echo "Error: File "$plot_file "does not exist"
   fi

   dat=$((dat+1))
   plot_file=$FILE$dat".dat"
   done
fi
