#!/bin/bash -e

t=300;

dat=$1
while [ $dat -lt $t ];
do
g=$(echo "scale=5; ($dat)/$t" | bc)

if [ $dat -eq 0 ] 
then
g=.00000
fi

echo $dat
../Graphics/cyl-density-log.py jet_"$dat".dat jet-"$g".png
j=`echo jet-"$g".png | sed 's/-./-/'`
mv jet-"$g".png $j
dat=$((dat+1))
done

for i in *.png; do j=`echo $i | sed 's/-./-/'`; mv $i $j; done
