#!/bin/bash

frames=$1

if [ -z "$frames" ]
then
   echo " "
   echo "Simple movie of PNG files using MENCODER"
   echo " "
   echo "Execute this file in your terminal as:"
   echo "   $ ./mencoder-avi fps"
   echo "where"
   echo "   fps: Frames per second you want"
   echo " "
   echo "Run this script inside the directory with"
   echo "all the PNG (not PDF) files you want to merge into a"
   echo "simple AVI movie:"
else

   opt="vbitrate=21600000"

   mencoder "mf://*.png"  -oac copy -mf fps=$frames -o test_N_fps$1.avi -ovc lavc -lavcopts vcodec=mpeg4:$opt
fi
