repos:
  - repo: local
    hooks:
      - id: trailing-whitespace
        name: Remove whitespaces
        entry: trailing-whitespace-fixer
        language: system
        types: [text]
      - id: end-of-file-fixer
        name: Fix end of file
        entry: end-of-file-fixer
        language: system
        types: [text]
      - id: debug-statements
        name: Debug statements
        entry: debug-statement-hook
        language: system
        types: [python]
      - id: check-merge-conflict
        name: Check merge conflicts
        entry: check-merge-conflict
        language: system
        types: [python]
      # -----------------------------------------------------------------
      # Hook para clang-format (formatea el código C/C++ según un estilo)
      # -----------------------------------------------------------------
      - id: clang-format
        name: clang-format
        entry: clang-format        # Asume que clang-format está en tu PATH
        language: system          # Usa la instalación del sistema (o tu PATH)
        pass_filenames: true
        # 'types' o 'files' puede filtrar qué archivos se formatean.
        # Por ejemplo, para .c, .cpp, .h, .hpp:
        types: [c, c++]
        args:
          - --style=file  # Usa la configuración del archivo .clang-format si existe
          - -i            # Reescribe los archivos (in-place)
      - id: cpplint
        name: cpplint
        description: Static code analysis of C/C++ files
        language: python
        files: \.(h\+\+|h|hh|hxx|hpp|cuh|c|cc|cpp|cu|c\+\+|cxx|tpp|txx)$
        entry: cpplint
        args: ['--filter=-build/include_subdir, -whitespace/line_length,-whitespace/indent,-whitespace/comments,-legal/copyright,-runtime/references,-build/c++11,-build/namespaces']
        exclude: 3rd_party/
