##############################################
####### Makefile for Equation of State #######
##############################################
#---------------------------------------------
# Files are automatically included in
# compilation when the EOS variable is 
# specified. But, you can add them here.
#---------------------------------------------

PHYSICS += $(AZTPATH)/Src/physics/EOS/$(EOS).c
