##############################################
########### Makefile for Stiff EoS ###########
##############################################
#---------------------------------------------
# You can add here other functions helpful for 
# the equation of state manipulation
#---------------------------------------------

PHYSICS += $(AZTPATH)/Src/physics/EOS/$(EOS)/eos.c
