PHYSICS += $(AZTPATH)/Src/physics/RHD/HYDRO/cons_q.c \
           $(AZTPATH)/Src/physics/RHD/HYDRO/cons2prim.c \
           $(AZTPATH)/Src/physics/RHD/HYDRO/flux_f.c \
           $(AZTPATH)/Src/physics/RHD/HYDRO/flux_g.c \
           $(AZTPATH)/Src/physics/RHD/HYDRO/flux_h.c \
           $(AZTPATH)/Src/physics/RHD/HYDRO/prim2cons.c \
           $(AZTPATH)/Src/physics/RHD/HYDRO/sources.c \
           $(AZTPATH)/Src/physics/RHD/HYDRO/surface_volume.c
ifeq ($(INT),pvrs)
   PHYSICS += $(AZTPATH)/Src/RHD/HYDRO/amatrix.c
endif
