PHYSICS = $(AZTPATH)/Src/HD/fvector.c \
			 $(AZTPATH)/Src/HD/gvector.c \
		 	 $(AZTPATH)/Src/HD/hvector.c \
			 $(AZTPATH)/Src/HD/svector.c \
			 $(AZTPATH)/Src/HD/qvector.c \
			 $(AZTPATH)/Src/HD/q2uvector.c \
			 $(AZTPATH)/Src/HD/u2qvector.c \
			 $(AZTPATH)/Src/HD/surface.c

ifeq ($(INT),pvrs)
   PHYSICS += $(AZTPATH)/Src/HD/amatrix.c
endif
