###################################################
###### Makefile for Classical Hydrodynamics #######
###################################################

ifeq ($(HYDRO),True)
   include $(AZTPATH)/Src/physics/HD/HYDRO/Makefile
endif
