PHYSICS += $(AZTPATH)/Src/physics/HD/HYDRO/cons_q.c \
			  $(AZTPATH)/Src/physics/HD/HYDRO/cons2prim.c \
			  $(AZTPATH)/Src/physics/HD/HYDRO/flux_f.c \
			  $(AZTPATH)/Src/physics/HD/HYDRO/flux_g.c \
			  $(AZTPATH)/Src/physics/HD/HYDRO/flux_h.c \
			  $(AZTPATH)/Src/physics/HD/HYDRO/prim2cons.c \
			  $(AZTPATH)/Src/physics/HD/HYDRO/sources.c \
			  $(AZTPATH)/Src/physics/HD/HYDRO/surface_volume.c \

ifeq ($(INT),pvrs)
	PHYSICS += $(AZTPATH)/Src/HD/HYDRO/amatrix.c
endif
