#!/bin/bash

maxima << EOF

t : t$
x : r*cos(theta)$
y : r*sin(theta)$
z : z$

J : jacobian([t,x,y,z],[t,r,theta,z])$
iJ : trigsimp(J^^-1)$
/*g : matrix([-(1-2*M/r),2*M/r,0,0],[2*M/r,(1 + 2*M/r),0,0],[0,0,r^2,0],[0,0,0,1])$ */
g : matrix([-1,0,0,0],[0,1,0,0],[0,0,r^2,0],[0,0,0,r^2*sin(theta)^2])$ 
string(g)$

G : factor(ev(g))$

kill(eq1,eq2,u,v,bestlength,trylength,t,x,y,z,J,iJ,g,dt,dr,dtheta,dz,dT,dTR,dTTheta,dTZ,dRT,dR,dRTheta,dRZ,dThetaT,dThetaR,dTheta,dThetaZ,dZT,dZR,dZTheta,dZ,gg,gg1,r)$ 
stringout("Metric",values)$

EOF
